from .general_parser import GeneralParser

from .critical_damage_parser import CriticalDamageParser
from .delay_after_attack_parser import DelayAfterAttackParser
from .delay_after_skill_parser import DelayAfterSkillParser
from .long_short_ranged_physical_damage_parser import LongShortRangedPhysicalDamageParser
from .mhp_msp_parser import MHPMSPParser
from .recovery_parser import RecoveryParser
from .variable_cast_time_parser import VariableCastTimeParser

from .category_parser import CategoryParser